---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omada-controller

images:
- name: mbentley/omada-controller
  newTag: "5.13"

resources:
  - ../base
  - certificate.yaml
  - ingress.yml

patches:
  - path: overlays/service.yml
